tokenizer_id: cc12m/rgb_ViTB-UNetP4_16k_224-448
tokenizers_root: ./tokenizer_ckpts
data_root: /path/to/dataset
split: train
n_crops: '1'
min_crop_scale: 0.8
input_size: 224
task: rgb
mask_value: null
resample_mode: null
corrupt_samples_log: null
verbose: false
dryrun: false
device: cuda
seed: 0
folder_suffix: dvae_BUa_224
num_workers: 16
pin_mem: false
no_pin_mem: true
batch_size_dataloader: 64
batch_size: 64
world_size: 1
local_rank: -1
dist_on_itp: false
dist_url: env://
force_load_crop: false
