config: ''
run_name: auto
patch_size: 16
input_size_min: 224
input_size_max: 512
input_size_sd: 512
max_input_size: false
resolution_step: 32
input_size_enc: null
encoder_type: vit_s_enc
post_mlp: false
no_post_mlp: true
encoder_ckpt: null
full_ckpt: null
freeze_enc: false
no_freeze_enc: true
dec_transformer_dropout: 0.2
quantizer_type: lucid
codebook_size: 8192
latent_dim: 32
norm_codes: false
no_norm_codes: true
norm_latents: false
no_norm_latents: true
codebook_weight: 1.0
quantizer_ema_decay: 0.8
coef_ema_dead_code: 4.0
code_replacement_policy: batch_random
commitment_weight: 1.0
kmeans_init: false
no_kmeans_init: true
cls_free_guidance_dropout: 0.2
guidance_scale: 2.5
cond_scale: 0.8
dynamic_guidance: false
masked_cfg: false
no_masked_cfg: true
masked_cfg_low: 0
masked_cfg_high: null
loss_fn: mse
sd_path: runwayml/stable-diffusion-v1-5
pretrained_cn: false
adapter: null
batch_size: 256
batch_size_eval: null
epochs: 100
save_ckpt_freq: 10
opt: adamw
opt_eps: 1e-8
opt_betas: '[0.9'
clip_grad: null
skip_grad: null
momentum: 0.9
weight_decay: 0.05
weight_decay_end: null
blr: 1e-4
warmup_lr: 1e-6
min_lr: 0.0
warmup_epochs: 40
warmup_steps: -1
dtype: float16
model_ema: true
model_ema_decay: 0.9999
model_ema_force_cpu: false
model_ema_update_freq: 1
hflip: 0.5
domain: rgb
mask_value: null
include_caption: false
data_path: data_constants.IMAGENET_TRAIN_PATH
eval_data_path: null
imagenet_default_mean_and_std: false
min_crop_scale: 0.8
cache_datasets: false
use_wds: false
no_use_wds: true
s3_endpoint: ''
s3_data_endpoint: null
wds_n_repeats: 1
wds_shuffle_buffer_tar: 1000
wds_shuffle_buffer_repeat: 1000
s3_multipart_chunksize_mb: 512
s3_multipart_threshold_mb: 512
dataset_size: null
dist_eval: false
no_dist_eval: true
step_eval: false
epoch_eval: true
num_eval_timesteps: 50
input_size_eval: 256
num_eval_metrics_samples: null
eval_freq: 1
eval_metrics_freq: 1
eval_image_log_freq: 5
num_logged_images: 100
eval_only: false
no_inception: false
output_dir: ''
device: cuda
seed: 0
resume: ''
auto_resume: false
no_auto_resume: true
start_epoch: 0
num_workers: 10
pin_mem: false
no_pin_mem: true
find_unused_params: false
no_find_unused_params: true
use_xformer: false
log_wandb: false
no_log_wandb: true
wandb_project: null
wandb_entity: null
wandb_run_name: null
wandb_tags: ''
show_user_warnings: false
world_size: 1
local_rank: -1
dist_on_itp: false
dist_url: env://
s3_path: ''
s3_save_dir: ''
